In [ ]:
## NumPy, we can create arrays, work with matrices, and perform mathematical operations very efficiently.

In [4]:
import numpy as np

In [5]:
!pip install numpy



[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

In [7]:
### creating 1d array using numpy
arr1 = np.array([1,2,3,4,5])
print(arr1)
type(arr1)
print(arr1.shape)

[1 2 3 4 5]
(5,)


In [8]:
arr2= np.array([1,2,3,4,5])
arr2.reshape(1,5) ## in 2d array the closed braces will be 2 
arr2.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [9]:
#### 2d array
arr3 = np.array([[1,2,3,4,5], [5,6,7,8,9]])
print(arr3)
print(arr3.shape) ### the no of rows and colums should be same otherwise a error would occur



[[1 2 3 4 5]
 [5 6 7 8 9]]
(2, 5)


In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
### identity matrix
np.eye(3)  ## diagnol elemenst will be one remaining will be 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
### attributes of numpy array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

(2, 3)
2
6
int64
8


In [15]:
### numpy vector operations
arr1  = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

### element wise addtion
print("addition",arr1+arr2)

### element wise substraction 
print("substraction",arr1-arr2)

### element wise multiplication 
print("multiplication",arr1*arr2)

### element wise division 
print("division",arr1/arr2)

addition [11 22 33 44 55]
substraction [ -9 -18 -27 -36 -45]
multiplication [ 10  40  90 160 250]
division [0.1 0.1 0.1 0.1 0.1]


In [16]:
### universal functions
arr = np.array([1,2,3,4,5])

##### square root
print(np.sqrt(arr))

## exponential
print(np.exp(arr))

### sine
print(np.sin(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [17]:
## array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
arr[0][0]

np.int64(1)

In [19]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [22]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [25]:
###### modifying the elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [26]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [27]:
###### statistical concepts  - normalization
### to have a mean of 0 and std of 1
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std = np.std(data)
normalized_data = (data - mean) / std
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

5.5
5.5
2.8722813232690143
8.25


In [38]:
### logical operation
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data > 5
data[(data>=5) | (data<=10)]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])